server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/threads_web_services?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "gI9y2dncxGq6Tb8LCAGsIX5Ngs9RxN9qeRGHTapgvf52RKiEtWrBCfRkGWB350it"